self-hosted-runner:
  labels:
    - comparevi
    - capability-ingress
    - docker-lane
    - labview-2026
    - lv32

paths:
  .github/workflows/release.yml:
    ignore:
      - 'SC2016:info:.*Expressions don''t expand in single quotes'
