name: "Compare VI (composite)"
description: "Compare two LabVIEW (.vi) files using NI LVCompare (LabVIEW 2025 Q3). Composite action for self-hosted Windows runners with full CLI flag pass-through."
author: "compare-vi-cli-action maintainers"
branding:
  icon: "git-merge"
  color: "blue"

inputs:
  base:
    description: "Path to the base .vi file"
    required: true
  head:
    description: "Path to the head .vi file"
    required: true
  lvComparePath:
    description: "Full path to LVCompare.exe, if not on PATH"
    required: false
  lvCompareArgs:
    description: "Additional CLI flags for LVCompare.exe (space-delimited)"
    required: false
    default: ""
  fail-on-diff:
    description: "Fail the job if differences are found"
    required: false
    default: "true"
  working-directory:
    description: "Directory to run LVCompare from (sets process CWD for relative paths)"
    required: false
    default: ""

outputs:
  diff:
    description: "true if differences were found"
    value: ${{ steps.run_compare.outputs.diff }}
  exitCode:
    description: "Raw exit code from LVCompare"
    value: ${{ steps.run_compare.outputs.exitCode }}
  cliPath:
    description: "Resolved path to LVCompare.exe"
    value: ${{ steps.run_compare.outputs.cliPath }}
  command:
    description: "Exact command line executed (for auditing)"
    value: ${{ steps.run_compare.outputs.command }}

runs:
  using: "composite"
  steps:
    - id: run_compare
      name: Run LVCompare
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        . "$PSScriptRoot\scripts\CompareVI.ps1"

        $wd = '${{ inputs.working-directory }}'
        $outPath = $env:GITHUB_OUTPUT
        $sumPath = $env:GITHUB_STEP_SUMMARY

        $result = Invoke-CompareVI -Base '${{ inputs.base }}' -Head '${{ inputs.head }}' `
          -LvComparePath '${{ inputs.lvComparePath }}' `
          -LvCompareArgs '${{ inputs.lvCompareArgs }}' `
          -WorkingDirectory $wd `
          -FailOnDiff ([System.Convert]::ToBoolean('${{ inputs.fail-on-diff }}')) `
          -GitHubOutputPath $outPath `
          -GitHubStepSummaryPath $sumPath

        # Expose outputs explicitly in case Invoke-CompareVI was called with custom paths
        "exitCode=$($result.ExitCode)"   >> $env:GITHUB_OUTPUT
        "cliPath=$($result.CliPath)"     >> $env:GITHUB_OUTPUT
        "command=$($result.Command)"     >> $env:GITHUB_OUTPUT
        $diffLower = if ($result.Diff) { 'true' } else { 'false' }
        "diff=$diffLower"                 >> $env:GITHUB_OUTPUT
