name: Validate
on: { workflow_dispatch: {} }
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Session index post
      uses: ./.github/actions/session-index-post
