name: Wire Invoker (stop)
description: Wire marker for invoker stop phase
inputs:
  results-dir:
    description: Results directory
    required: false
    default: results/fixture-drift
runs:
  using: composite
  steps:
  - name: Wire I2
    shell: pwsh
    run: |
      $rd = '${{ inputs.results-dir }}'
      $env:WIRE_PHASE='I2'
      pwsh -NoLogo -NoProfile -Command @'
        param($Phase,$Dir)
        $ErrorActionPreference = "Stop"
        if ([string]::IsNullOrWhiteSpace($Dir)) { $Dir = 'results/fixture-drift' }
        $wireDir = Join-Path $Dir '_wire'
        New-Item -ItemType Directory -Force -Path $wireDir | Out-Null
        $payload = [ordered]@{ phase=$Phase; timestamp=(Get-Date).ToUniversalTime().ToString('o'); kind='invoker-stop' }
        $outPath = Join-Path $wireDir ("{0}.json" -f $Phase)
        ($payload | ConvertTo-Json -Depth 4) | Out-File -FilePath $outPath -Encoding utf8
      '@ -Args $env:WIRE_PHASE, $rd

