name: DEPRECATED — CI Orchestrated v2 (use strategy=single)

on:
  # Keep only manual dispatch to avoid accidental use
  workflow_dispatch:
    inputs:
      include_integration:
        description: 'Include Integration-tagged tests'
        required: false
        default: 'true'
        type: choice
        options: ['true', 'false']
      sample_id:
        description: 'Sampling correlation id (prevents cancels)'
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.inputs.sample_id || github.ref }}
  cancel-in-progress: true

jobs:
  deprecated:
    runs-on: ubuntu-latest
    steps:
    - name: Deprecation notice
      shell: bash
      run: |
        cat >> "$GITHUB_STEP_SUMMARY" <<'EOF'
        ### Deprecated Workflow

        - Use `CI Orchestrated (deterministic chain)` with `strategy=single`.
        - This file remains only for manual fallback and will be removed after probation.
        EOF
