name: Develop Two-Greens (orchestrated)

on:
  workflow_run:
    workflows: ["CI Orchestrated (deterministic chain)"]
    types: [completed]

permissions:
  contents: read
  actions: read
  pull-requests: write
  issues: write

jobs:
  two-green:
    if: ${{ vars.ORCH_TWO_GREENS == '1' && github.event.workflow_run.head_branch == 'develop' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Apply agent toggles
        uses: ./.github/actions/apply-agent-toggles
      - name: Check last two orchestrated runs on develop (paged)
        id: check
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          owner_repo="${GITHUB_REPOSITORY}"
          owner="${owner_repo%%/*}"
          repo="${owner_repo##*/}"
          wf_name="CI Orchestrated (deterministic chain)"
          wf_list=$(curl -sS -H "Authorization: Bearer ${GH_TOKEN}" -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${owner}/${repo}/actions/workflows")
          wf_id=$(echo "$wf_list" | jq -r --arg n "$wf_name" '.workflows[] | select(.name==$n) | .id' | head -n1)
          if [ -z "$wf_id" ]; then
            echo "::error::Workflow id not found for name: $wf_name"; exit 2
          fi
          runs=$(curl -sS -H "Authorization: Bearer ${GH_TOKEN}" -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${owner}/${repo}/actions/workflows/${wf_id}/runs?branch=develop&per_page=10&page=1")
          # Filter only completed runs and take the two most recent
          cur=$(echo "$runs" | jq -r '.workflow_runs | map(select(.status=="completed")) | .[0].conclusion // ""')
          prev=$(echo "$runs" | jq -r '.workflow_runs | map(select(.status=="completed")) | .[1].conclusion // ""')
          echo "current: $cur, previous: $prev"
          if [ "$cur" = "success" ] && [ "$prev" = "success" ]; then
            echo "two_green=true" >> "$GITHUB_OUTPUT"
          else
            echo "two_green=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

      - name: Open PR to remove ci-orchestrated-v2.yml
        if: ${{ steps.check.outputs.two_green == 'true' && hashFiles('.github/workflows/ci-orchestrated-v2.yml') != '' }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: chore/remove-orchestrated-v2
          commit-message: "chore: remove deprecated ci-orchestrated-v2.yml after two green cycles (#88)"
          title: "chore: remove deprecated ci-orchestrated-v2.yml"
          body: |
            Removing ci-orchestrated-v2.yml as the unified orchestrated workflow has achieved two consecutive green runs on develop.
            References #88.
          delete-branch: true
          add-paths: .github/workflows/ci-orchestrated-v2.yml
          author: GitHub Actions <actions@github.com>

      - name: Post two-green summary
        if: always()
        shell: bash
        run: |
          cat >> "$GITHUB_STEP_SUMMARY" <<'EOF'
          ### Develop: Two Consecutive Green Orchestrated Runs
          - Workflow: CI Orchestrated (deterministic chain)
          - Branch: develop
          EOF

      - name: Comment on issue #88 (signal)
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          body=$(cat <<'EOF'
          Develop has two consecutive green runs for CI Orchestrated (deterministic chain).

          - Branch: `develop`
          - Workflow: CI Orchestrated (deterministic chain)
          EOF
          )
          gh issue comment 88 -b "$body"
