name: .NET Shared Library

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/dotnet-shared.yml'
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/dotnet-shared.yml'
  workflow_dispatch:
    inputs:
      sample_id:
        description: 'Sampling correlation id (prevents cancels)'
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.inputs.sample_id || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Node dependencies
        run: npm ci
      - name: Generate schemas
        run: npm run schemas:generate
      - name: Ensure schema artifacts are in sync
        run: |
          git diff --name-only --exit-code docs/schema/generated src/CompareVi.Shared/Schemas || (git diff docs/schema/generated src/CompareVi.Shared/Schemas && exit 1)
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore src/CompareVi.Shared/CompareVi.Shared.csproj
      - name: Build
        run: dotnet build -c Release src/CompareVi.Shared/CompareVi.Shared.csproj --no-restore
      - name: Test
        run: dotnet test -c Release src/CompareVi.Shared.Tests/CompareVi.Shared.Tests.csproj --no-build
      - name: Pack
        run: dotnet pack -c Release src/CompareVi.Shared/CompareVi.Shared.csproj -o artifacts --no-build
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: comparevi-shared-nuget
          path: artifacts/*.nupkg
          if-no-files-found: error
