name: Fixture Drift Validation

on:
  pull_request:
  workflow_dispatch:

jobs:
  validate-ubuntu:
    name: Fixture Drift (Ubuntu)
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fixture Drift Orchestrator
        uses: ./.github/actions/fixture-drift
        with:
          render-report: 'false'
          comment-on-fail: 'true'
          upload-artifacts: 'true'
          artifact-name: fixture-drift-ubuntu

  validate-windows:
    name: Fixture Drift (Windows)
    runs-on: [self-hosted, Windows, X64]
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fixture Drift Orchestrator
        uses: ./.github/actions/fixture-drift
        with:
          render-report: 'true'
          comment-on-fail: 'true'
          upload-artifacts: 'true'
          artifact-name: fixture-drift-windows

      - name: Runner Unblock Guard (process/jobs snapshot)
        if: always()
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $snap = [ordered]@{}
          try {
            $procs = @(Get-Process -ErrorAction SilentlyContinue | Where-Object { $_.ProcessName -in @('conhost','pwsh','LabVIEW','LVCompare') } | Select-Object ProcessName,Id,StartTime)
            $jobs  = @(Get-Job -ErrorAction SilentlyContinue | Select-Object Id,Name,State,HasMoreData)
            $snap.processes = $procs
            $snap.jobs = $jobs
            $outDir = Join-Path (Get-Location) 'results/fixture-drift'
            New-Item -ItemType Directory -Force -Path $outDir | Out-Null
            $path = Join-Path $outDir 'runner-unblock-snapshot.json'
            $snap | ConvertTo-Json -Depth 5 | Out-File -FilePath $path -Encoding utf8

            # Optional cleanup behind env toggle UNBLOCK_GUARD=1
            $cleanupNote = ''
            if ($env:UNBLOCK_GUARD -eq '1') {
              $stoppedLV = 0; $stoppedLVC = 0; $stoppedJobs = 0
              try { Get-Process -Name 'LabVIEW' -ErrorAction SilentlyContinue | ForEach-Object { try { Stop-Process -Id $_.Id -ErrorAction SilentlyContinue; $stoppedLV++ } catch {} } } catch {}
              try { Get-Process -Name 'LVCompare' -ErrorAction SilentlyContinue | ForEach-Object { try { Stop-Process -Id $_.Id -ErrorAction SilentlyContinue; $stoppedLVC++ } catch {} } } catch {}
              try { $gj = @(Get-Job -ErrorAction SilentlyContinue); foreach ($j in $gj) { try { Stop-Job -Job $j -ErrorAction SilentlyContinue; Remove-Job -Job $j -Force -ErrorAction SilentlyContinue; $stoppedJobs++ } catch {} } } catch {}
              $cleanupNote = ('Cleanup: LabVIEW={0}, LVCompare={1}, Jobs={2}' -f $stoppedLV,$stoppedLVC,$stoppedJobs)
            }
            $lines = @('### Runner Unblock Guard','')
            $lines += ('- Process count: {0}' -f $procs.Count)
            $lines += ('- Pester job count: {0}' -f $jobs.Count)
            $lines += ''
            $lines += ('Snapshot: {0}' -f $path)
            if ($cleanupNote) { $lines += ('- ' + $cleanupNote) }
            $lines -join "`n" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append -Encoding utf8
          } catch { Write-Host "::warning::Unblock guard failed: $_" }
