name: Fixture Drift Validation

on:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    name: Fixture Drift
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fixture Drift Orchestrator
        uses: ./.github/actions/fixture-drift
        with:
          render-report: 'false'
          comment-on-fail: 'true'
          upload-artifacts: 'true'
          artifact-name: fixture-drift
