name: markdownlint

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint changed Markdown (PR)
        if: github.event_name == 'pull_request'
        run: npm run lint:md:changed

      - name: Lint all Markdown (notice-only)
        if: github.event_name != 'pull_request'
        continue-on-error: true
        run: npm run lint:md
