name: Policy Guard (Upstream)

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - develop
      - release/**

concurrency:
  group: policy-guard-upstream-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  policy-guard:
    name: policy-guard
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v5
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: Run policy guard
        run: node tools/priority/check-policy.mjs
