name: PR Auto-merge (on label)

on:
  pull_request_target:
    types: [labeled, synchronize, reopened]

permissions:
  pull-requests: write
  contents: write

jobs:
  enable-automerge:
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge (merge method)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: MERGE

