name: Integration Runbook Validation

on:
  workflow_dispatch:
    inputs:
      sample_id:
        description: 'Sampling correlation id (prevents cancels)'
        required: false
        type: string
  push:
    branches:
      - develop
      - release/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.inputs.sample_id || github.ref }}
  cancel-in-progress: true

jobs:
  runbook-check:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    runs-on: [self-hosted, Windows, X64]
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PowerShell Core
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
        # (Using setup-python only to ensure UTF-8 locale; PowerShell 7 available by default on windows-latest.)

      - name: Run Runbook Core Phases
        shell: pwsh
        run: |
          pwsh -File scripts/Invoke-IntegrationRunbook.ps1 -Phases Prereqs,CanonicalCli,ViInputs -JsonReport runbook-ci.json -PassThru | Out-Null
          Get-Content runbook-ci.json

      - name: Upload Runbook Artifact
        uses: actions/upload-artifact@v4
        with:
          name: integration-runbook-result
          path: runbook-ci.json

      - name: Validate JSON Schema (basic)
        shell: pwsh
        run: |
          $json = Get-Content runbook-ci.json -Raw | ConvertFrom-Json
          if ($json.schema -ne 'integration-runbook-v1') { throw 'Schema mismatch' }
          if (-not $json.phases) { throw 'No phases in runbook output' }
