name: Smoke test Compare VI action

on:
  workflow_dispatch:
    inputs:
      base:
        description: "Absolute or workspace-relative path to base .vi"
        required: true
        type: string
      head:
        description: "Absolute or workspace-relative path to head .vi"
        required: true
        type: string
      lvComparePath:
        description: "Full path to LVCompare.exe (if not on PATH)"
        required: false
        type: string
        default: ""
      lvCompareArgs:
        description: "Extra flags for LVCompare.exe (space-delimited; quotes supported)"
        required: false
        type: string
        default: ""
      fail_on_diff:
        description: "Fail the job if differences are found"
        required: false
        type: choice
        options: ["true", "false"]
        default: "true"

jobs:
  compare:
    runs-on: [self-hosted, Windows]
    steps:
      - uses: actions/checkout@v5

      - name: Run local action
        id: compare
        uses: ./
        with:
          base: ${{ github.event.inputs.base }}
          head: ${{ github.event.inputs.head }}
          lvComparePath: ${{ github.event.inputs.lvComparePath }}
          lvCompareArgs: ${{ github.event.inputs.lvCompareArgs }}
          fail-on-diff: ${{ github.event.inputs.fail_on_diff }}

      - name: Echo outputs
        if: always()
        shell: pwsh
        run: |
          Write-Host "diff      = ${{ steps.compare.outputs.diff }}"
          Write-Host "exitCode  = ${{ steps.compare.outputs.exitCode }}"
          Write-Host "cliPath   = ${{ steps.compare.outputs.cliPath }}"
