name: Pester tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.ps1'
      - '**/*.psm1'
      - 'scripts/**'
      - 'tools/**'
      - 'module/**'
      - 'tests/**'
      - 'action.yml'
      - 'fixtures.manifest.json'
      - 'VI*.vi'
      - 'docs/schemas/**'
  push:
    branches: [ main ]
    paths:
      - '**/*.ps1'
      - '**/*.psm1'
      - 'scripts/**'
      - 'tools/**'
      - 'module/**'
      - 'tests/**'
      - 'action.yml'
      - 'fixtures.manifest.json'
      - 'VI*.vi'
      - 'docs/schemas/**'
  workflow_dispatch:
    inputs:
      include_integration:
        description: "Include Integration-tagged tests (may invoke mock CLI)"
        required: false
        default: 'false'
        type: choice
        options: ['false','true']
      sample_id:
        description: 'Sampling correlation id (prevents cancels)'
        required: false
        type: string

jobs:
  pester:
    uses: ./.github/workflows/pester-reusable.yml
    secrets: inherit
    with:
      include_integration: ${{ inputs.include_integration || 'false' }}
      install_pester: ${{ 'true' }}
      sample_id: ${{ inputs.sample_id || '' }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.inputs.sample_id || github.ref }}
  cancel-in-progress: true

