name: Test (mock LVCompare) - DEPRECATED

# NOTE: This workflow is deprecated with the canonical-only CLI path policy.
# Use unit tests (test-pester.yml) for mock-based testing instead.
# This workflow is kept for manual dispatch only for backward compatibility.

on:
  workflow_dispatch: {}

jobs:
  mock-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Validate canonical fixtures
        shell: pwsh
        run: pwsh -NonInteractive -File tools/Validate-Fixtures.ps1 -MinBytes 32 -Quiet

      - name: Prepare mock LVCompare
        shell: pwsh
        run: |
          $mockDir = Join-Path $env:RUNNER_TEMP 'mock'
          New-Item -ItemType Directory -Path $mockDir -Force | Out-Null
          $cmdPath = Join-Path $mockDir 'LVCompare.cmd'
          $lines = @(
            '@echo off',
            'REM Mock LVCompare: exit 0 if base==head; else 1. Allow override via FORCE_EXIT.',
            'if not "%FORCE_EXIT%"=="" exit /b %FORCE_EXIT%',
            'if "%~f1"=="%~f2" exit /b 0',
            'exit /b 1'
          )
          $lines | Set-Content -LiteralPath $cmdPath -Encoding ASCII
          Write-Host ("Mock at: {0}" -f $cmdPath)
          echo ("MOCK_PATH={0}" -f $mockDir) | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

      - name: Create sample files
        shell: pwsh
        run: |
          $wd = Join-Path $env:RUNNER_TEMP 'vis'
          New-Item -ItemType Directory -Path $wd -Force | Out-Null
          New-Item -ItemType File -Path (Join-Path $wd 'a.vi') -Force | Out-Null
          New-Item -ItemType File -Path (Join-Path $wd 'b.vi') -Force | Out-Null
          echo ("WD={0}" -f $wd) | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

      - name: Export mock vars
        id: vars
        shell: pwsh
        run: |
          if (-not $env:WD) { throw 'WD not set' }
          if (-not $env:MOCK_PATH) { throw 'MOCK_PATH not set' }
          "WD=$($env:WD)"         >> $env:GITHUB_OUTPUT
          "MOCK_PATH=$($env:MOCK_PATH)" >> $env:GITHUB_OUTPUT

      - name: Case 1 - diff true, fail-on-diff=false
        id: c1
        uses: ./
        with:
          working-directory: ${{ steps.vars.outputs.WD }}
          base: a.vi
          head: b.vi
          lvComparePath: ${{ steps.vars.outputs.MOCK_PATH }}\\LVCompare.cmd
          lvCompareArgs: "--dummy \"C:\\Temp\\Spaced Path\\x\""
          fail-on-diff: "false"

      - name: Assert Case 1 outputs
        shell: pwsh
        run: |
          if ('${{ steps.c1.outputs.diff }}' -ne 'true') { throw "Expected diff=true" }
          if ('${{ steps.c1.outputs.exitCode }}' -ne '1') { throw "Expected exitCode=1" }

      - name: Case 2 - diff true, fail-on-diff=true (should fail step)
        id: c2
        continue-on-error: true
        uses: ./
        with:
          working-directory: ${{ steps.vars.outputs.WD }}
          base: a.vi
          head: b.vi
          lvComparePath: ${{ steps.vars.outputs.MOCK_PATH }}\\LVCompare.cmd
          fail-on-diff: "true"

      - name: Assert Case 2 failed and outputs present
        shell: pwsh
        run: |
          if ('${{ steps.c2.outcome }}' -ne 'failure') { throw "Expected step failure" }
          if ('${{ steps.c2.outputs.diff }}' -ne 'true') { throw "Expected diff=true" }
          if ('${{ steps.c2.outputs.exitCode }}' -ne '1') { throw "Expected exitCode=1" }

      - name: Case 3 - no diff, equal files
        id: c3
        uses: ./
        with:
          working-directory: ${{ steps.vars.outputs.WD }}
          base: a.vi
          head: a.vi
          lvComparePath: ${{ steps.vars.outputs.MOCK_PATH }}\\LVCompare.cmd
          fail-on-diff: "true"

      - name: Assert Case 3 outputs
        shell: pwsh
        run: |
          if ('${{ steps.c3.outputs.diff }}' -ne 'false') { throw "Expected diff=false" }
          if ('${{ steps.c3.outputs.exitCode }}' -ne '0') { throw "Expected exitCode=0" }

      - name: Case 4 - LVCOMPARE_PATH discovery
        id: c4
        uses: ./
        env:
          LVCOMPARE_PATH: ${{ steps.vars.outputs.MOCK_PATH }}\LVCompare.cmd
        with:
          working-directory: ${{ steps.vars.outputs.WD }}
          base: a.vi
          head: b.vi
          fail-on-diff: "false"

      - name: Assert Case 4 outputs
        shell: pwsh
        run: |
          if ('${{ steps.c4.outputs.diff }}' -ne 'true') { throw "Expected diff=true" }
          if ('${{ steps.c4.outputs.exitCode }}' -ne '1') { throw "Expected exitCode=1" }

      - name: Expose mock on PATH
        shell: pwsh
        run: |
          echo ("PATH={0};{1}" -f '${{ steps.vars.outputs.MOCK_PATH }}', $env:PATH) | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

      - name: Case 5 - PATH discovery
        id: c5
        uses: ./
        with:
          working-directory: ${{ steps.vars.outputs.WD }}
          base: a.vi
          head: b.vi
          fail-on-diff: "false"

      - name: Assert Case 5 outputs
        shell: pwsh
        run: |
          if ('${{ steps.c5.outputs.diff }}' -ne 'true') { throw "Expected diff=true" }
          if ('${{ steps.c5.outputs.exitCode }}' -ne '1') { throw "Expected exitCode=1" }

      - name: Case 6 - unknown exit code should fail but keep outputs
        id: c6
        continue-on-error: true
        uses: ./
        env:
          FORCE_EXIT: '2'
        with:
          working-directory: ${{ steps.vars.outputs.WD }}
          base: a.vi
          head: b.vi
          lvComparePath: ${{ steps.vars.outputs.MOCK_PATH }}\LVCompare.cmd
          fail-on-diff: "false"

      - name: Assert Case 6 failure with outputs
        shell: pwsh
        run: |
          if ('${{ steps.c6.outcome }}' -ne 'failure') { throw "Expected step failure" }
          if ('${{ steps.c6.outputs.exitCode }}' -ne '2') { throw "Expected exitCode=2" }
          if ('${{ steps.c6.outputs.diff }}' -ne 'false') { throw "Expected diff=false" }

      - name: Comment results on PR (using XCLI_PAT)
        if: github.event_name == 'pull_request'
        shell: pwsh
        env:
          GH_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          XCLI_PAT: ${{ secrets.XCLI_PAT }}
        run: |
          $lines = @(
            '### Test (mock) results',
            '',
            "- Case 1: diff=${{ steps.c1.outputs.diff }}, exitCode=${{ steps.c1.outputs.exitCode }}",
            "- Case 2: outcome=${{ steps.c2.outcome }}, diff=${{ steps.c2.outputs.diff }}, exitCode=${{ steps.c2.outputs.exitCode }}",
            "- Case 3: diff=${{ steps.c3.outputs.diff }}, exitCode=${{ steps.c3.outputs.exitCode }}",
            "- Case 4: diff=${{ steps.c4.outputs.diff }}, exitCode=${{ steps.c4.outputs.exitCode }}",
            "- Case 5: diff=${{ steps.c5.outputs.diff }}, exitCode=${{ steps.c5.outputs.exitCode }}",
            "- Case 6: outcome=${{ steps.c6.outcome }}, diff=${{ steps.c6.outputs.diff }}, exitCode=${{ steps.c6.outputs.exitCode }}"
          ) -join "`n"
          $payload = @{ body = $lines } | ConvertTo-Json -Compress
          $headers = @{ Authorization = "Bearer $env:XCLI_PAT"; Accept = 'application/vnd.github+json'; 'User-Agent' = 'xcli-bot' }
          $uri = "https://api.github.com/repos/$env:GH_REPO/issues/$env:PR_NUMBER/comments"
          Invoke-RestMethod -Method POST -Uri $uri -Headers $headers -ContentType 'application/json' -Body $payload

      - name: Generate HTML reports from outputs
        if: always()
        shell: pwsh
        run: |
          $outDir = Join-Path $env:RUNNER_TEMP 'mock-reports'
          New-Item -ItemType Directory -Force -Path $outDir | Out-Null
          $renderer = Join-Path $env:GITHUB_WORKSPACE 'scripts' 'Render-CompareReport.ps1'
          # Report for Case 1 (diff=true)
          & $renderer `
            -Command '${{ steps.c1.outputs.command }}' `
            -ExitCode ${{ steps.c1.outputs.exitCode }} `
            -Diff '${{ steps.c1.outputs.diff }}' `
            -CliPath '${{ steps.c1.outputs.cliPath }}' `
            -OutputPath (Join-Path $outDir 'case-1.html')
          # Report for Case 3 (no diff)
          & $renderer `
            -Command '${{ steps.c3.outputs.command }}' `
            -ExitCode ${{ steps.c3.outputs.exitCode }} `
            -Diff '${{ steps.c3.outputs.diff }}' `
            -CliPath '${{ steps.c3.outputs.cliPath }}' `
            -OutputPath (Join-Path $outDir 'case-3.html')

      - name: Upload mock HTML reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mock-html-reports
          path: ${{ runner.temp }}/mock-reports/*.html
