name: Pester tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      include_integration:
        description: "Include Integration-tagged tests (may invoke mock CLI)"
        required: false
        default: 'false'
        type: choice
        options: ['false','true']

jobs:
  pester:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5

      - name: Install Pester v5
        shell: pwsh
        run: |
          Install-Module -Name Pester -RequiredVersion 5.4.0 -Force -SkipPublisherCheck -Scope CurrentUser

      - name: Run unit tests (Pester v5, repo-local)
        shell: pwsh
        run: |
          if ('${{ inputs.include_integration }}' -ieq 'true') {
            ./tools/Run-Pester.ps1 -IncludeIntegration
          } else {
            ./tools/Run-Pester.ps1
          }

      - name: Publish Pester summary
        if: always()
        shell: pwsh
        run: |
          pwsh -File scripts/Write-PesterSummaryToStepSummary.ps1 -ResultsDir 'tests/results'
          $idx = Join-Path 'tests/results' 'session-index.json'
          if (Test-Path $idx) {
            try {
              $ix = Get-Content $idx -Raw | ConvertFrom-Json
              if ($ix.stepSummary) {
                $intro = @('','### Session Overview','') -join "`n"
                $intro | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append -Encoding utf8
                $ix.stepSummary | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append -Encoding utf8
              } else {
                "`nSession index: tests/results/session-index.json" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append -Encoding utf8
              }
            } catch { Write-Host '::warning::failed to append session index step summary' }
          }

      - name: Upload Pester artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pester-results
          path: |
            tests/results/pester-results.xml
            tests/results/pester-summary.txt
            tests/results/pester-summary.json
            tests/results/pester-artifacts.json
            tests/results/pester-artifacts-trail.json
            tests/results/pester-leak-report.json
            tests/results/session-index.json

      - name: Validate session index schema (schema-lite)
        if: always()
        shell: pwsh
        run: |
          $idx = 'tests/results/session-index.json'
          if (Test-Path $idx) {
            pwsh -File tools/Invoke-JsonSchemaLite.ps1 -JsonPath $idx -SchemaPath docs/schemas/session-index-v1.schema.json
            if ($LASTEXITCODE -ne 0) { Write-Host "Session index schema-lite returned code $LASTEXITCODE" }
          } else {
            Write-Host '::notice::session-index.json not present.'
          }
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
