name: Pester tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.ps1'
      - '**/*.psm1'
      - 'scripts/**'
      - 'tools/**'
      - 'module/**'
      - 'tests/**'
      - 'action.yml'
      - 'fixtures.manifest.json'
      - 'VI*.vi'
      - 'docs/schemas/**'
  push:
    branches: [ main ]
    paths:
      - '**/*.ps1'
      - '**/*.psm1'
      - 'scripts/**'
      - 'tools/**'
      - 'module/**'
      - 'tests/**'
      - 'action.yml'
      - 'fixtures.manifest.json'
      - 'VI*.vi'
      - 'docs/schemas/**'
  workflow_dispatch:
    inputs:
      include_integration:
        description: "Include Integration-tagged tests (may invoke mock CLI)"
        required: false
        default: 'false'
        type: choice
        options: ['false','true']

jobs:
  pester:
    runs-on: [self-hosted, Windows, X64]
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v5

      - name: Install Pester v5
        shell: pwsh
        run: |
          Install-Module -Name Pester -RequiredVersion 5.4.0 -Force -SkipPublisherCheck -Scope CurrentUser

      - name: Run unit tests (Pester v5, repo-local)
        shell: pwsh
        run: |
          if ('${{ inputs.include_integration }}' -ieq 'true') {
            ./tools/Run-Pester.ps1 -IncludeIntegration
          } else {
            ./tools/Run-Pester.ps1
          }

      - name: Publish Pester summary
        if: always()
        shell: pwsh
        run: |
          pwsh -NonInteractive -File scripts/Write-PesterSummaryToStepSummary.ps1 -ResultsDir 'tests/results'

      - name: Ensure session index (fallback)
        if: always()
        shell: pwsh
        run: |
          pwsh -File tools/Ensure-SessionIndex.ps1 -ResultsDir 'tests/results' -SummaryJson 'pester-summary.json'

      - name: Session index post
        if: always()
        uses: ./.github/actions/session-index-post
        with:
          results-dir: tests/results
          validate-schema: true
          upload: true
          artifact-name: session-index

      - name: Upload Pester artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pester-results
          path: |
            tests/results/pester-results.xml
            tests/results/pester-summary.txt
            tests/results/pester-summary.json
            tests/results/pester-artifacts.json
            tests/results/pester-artifacts-trail.json
            tests/results/pester-leak-report.json
            tests/results/session-index.json

      - name: Runner Unblock Guard
        if: always()
        uses: ./.github/actions/runner-unblock-guard
        with:
          snapshot-path: tests/results/runner-unblock-snapshot.json
          cleanup: ${{ env.UNBLOCK_GUARD == '1' }}
          process-names: 'conhost,pwsh,LabVIEW,LVCompare'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
