name: Validate

on:
  pull_request:
    branches: [ main, 'release/*' ]
  push:
    branches: [ main, 'release/*' ]
  workflow_dispatch:
    inputs:
      summary-verbose:
        description: 'Emit verbose fixture summary (sets SUMMARY_VERBOSE=true)'
        required: false
        default: 'false'

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Branch protection gate (main/release only)
        uses: ./.github/actions/branch-protection-gate
        with:
          branch: ${{ github.ref_name }}
          strict: 'true'
          fail-on-no-access: 'true'
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') || (github.ref == 'refs/heads/develop' && vars.ENFORCE_PROTECTION_ON_DEVELOP != '0') }}
  lint:
    runs-on: ubuntu-latest
    needs: [protect]
    permissions:
      contents: read
      issues: read
    steps:
      - uses: actions/checkout@v5

      - name: Install actionlint
        run: |
          mkdir -p ./bin
          curl -sSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash -s -- latest ./bin

      - name: Run actionlint
        run: |
          ./bin/actionlint -color

      - name: Lint unanchored dot-sourcing (non-blocking)
        shell: pwsh
        continue-on-error: true
        run: |
          pwsh -NonInteractive -File tools/Lint-DotSourcing.ps1 -WarnOnly

      - name: Lint inline-if in format (-f)
        shell: pwsh
        run: pwsh -NonInteractive -File tools/Lint-InlineIfInFormat.ps1

      - name: Install markdownlint-cli
        run: |
          npm install -g markdownlint-cli

      - name: Run markdownlint
        run: |
          markdownlint "**/*.md" --ignore node_modules

      - name: Local markdown link check (intra-repo)
        shell: pwsh
        run: |
          # Simple intra-repo link checker: scans markdown for (./...) links and verifies files exist.
          $ErrorActionPreference = 'Stop'
          $mdFiles = Get-ChildItem -Path . -Recurse -Include *.md
          $errors = @()
          foreach ($file in $mdFiles) {
            $text = Get-Content -LiteralPath $file.FullName -Raw
            $matches = [regex]::Matches($text, '\]\((\.\/?[^)#\s]+)\)')
            foreach ($m in $matches) {
              $rel = $m.Groups[1].Value
              if ($rel -like 'http*' -or $rel -like '#*') { continue }
              # Strip anchors like file.md#section
              $pathOnly = $rel.Split('#')[0]
              $target = Join-Path $file.DirectoryName $pathOnly
              if (-not (Test-Path -LiteralPath $target)) {
                $errors += "[$($file.FullName)] broken link -> $rel (resolved: $target)"
              }
            }
          }
          if ($errors.Count -gt 0) {
            Write-Host 'Broken intra-repo links detected:'
            $errors | ForEach-Object { Write-Host " - $_" }
            exit 2
          } else {
            Write-Host 'Intra-repo markdown links OK.'
          }

      - name: Lint PR template semantics
        shell: pwsh
        run: pwsh -NonInteractive -File tools/Lint-PullRequestTemplate.ps1

      - name: Lint PR body (summary, non-blocking)
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GH_TOKEN: ${{ github.token }}
        shell: pwsh
        run: |
          try {
            $pr = '${{ github.event.pull_request.number }}'
            $out = pwsh -NonInteractive -File tools/Lint-IssueAndPRBodies.ps1 -PR $pr -WarnOnly 2>&1 | Out-String
            $lines = @('### PR Body Lint (non-blocking)','```', $out.Trim(), '```')
            pwsh -NonInteractive -File tools/Write-StepSummary.ps1 -Lines $lines -Append | Out-Null
          } catch {
            Write-Host '::notice::PR body linter skipped or failed (non-blocking).'
          }

      - name: Proactive tracking suggestions (non-blocking)
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GH_TOKEN: ${{ github.token }}
        shell: pwsh
        continue-on-error: true
        run: |
          try {
            $text = pwsh -NonInteractive -File tools/Monitor-IssuesPRs.ps1 -Limit 50 2>&1 | Out-String
            $idx  = $text.IndexOf('### Suggestions')
            if ($idx -ge 0) {
              $sugg = $text.Substring($idx).Trim()
            } else {
              $sugg = "### Suggestions`n- None"
            }
            $lines = @('### Proactive Tracking (non-blocking)', $sugg)
            pwsh -NonInteractive -File tools/Write-StepSummary.ps1 -Lines $lines -Append | Out-Null
          } catch {
            Write-Host '::notice::Tracking suggestions skipped (non-blocking).'
          }

      - name: Labels sync summary (config vs live)
        shell: pwsh
        env:
          FAIL_LABELS_ON_MAIN: ${{ github.ref == 'refs/heads/main' && '1' || '0' }}
        run: |
          $fail = $false; if ($env:FAIL_LABELS_ON_MAIN -eq '1') { $fail = $true }
          pwsh -NonInteractive -File tools/Write-LabelsSyncSummary.ps1 -ConfigPath '.github/labels.yml' -FailOnMissing:$fail

      - name: Repo hygiene (warn-only)
        shell: pwsh
        continue-on-error: true
        run: pwsh -NonInteractive -File tools/Check-RepoHygiene.ps1 -WarnOnly

      - name: Repo hygiene (strict on protected branches)
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') }}
        shell: pwsh
        run: pwsh -NonInteractive -File tools/Check-RepoHygiene.ps1

      - name: Append required checks (branch rules hint)
        if: always()
        shell: pwsh
        run: |
          $lines = @(
            '### Required checks (copy for branch protections)',
            '- Pester (self-hosted) / preflight',
            '- Pester (self-hosted) / pester (dispatcher|fixtures|schema|comparevi|loop|runbook|orchestrator)',
            '- Fixture Drift Validation / Fixture Drift (Windows)',
            '- VI Binary Handling Gate / vi-binary-check',
            '- Validate / lint',
            '- markdownlint / lint'
          )
          pwsh -NonInteractive -File tools/Write-StepSummary.ps1 -Lines $lines -Append | Out-Null
          $doc = 'docs/BRANCH_RULES.md'
          $tail = if (Test-Path $doc) { "See: ./$doc" } else { 'Branch rules guide: docs/BRANCH_RULES.md (coming soon in issue #60)' }
          pwsh -NonInteractive -File tools/Write-StepSummary.ps1 -Text $tail -Append | Out-Null

  fixtures:
    runs-on: [self-hosted, Windows, X64]
    needs: [protect]
    env:
      FAIL_ON_NEW_STRUCTURAL: 'false' # toggle to 'true' to fail job on new structural fixture issues
      SUMMARY_VERBOSE: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.summary-verbose || 'false' }}
    steps:
      - uses: actions/checkout@v5
      - name: Run fixture validator (JSON)
        shell: pwsh
        continue-on-error: true
        run: |
          $ErrorActionPreference = 'Stop'
          pwsh -NonInteractive -File tools/Validate-Fixtures.ps1 -Json -MinBytes 32 > fixture-validation.json
          $exit = $LASTEXITCODE
          if ($exit -ne 0) { Write-Host "::warning::Fixture validator exit code: $exit (non-blocking)" }
          $data = Get-Content fixture-validation.json -Raw | ConvertFrom-Json
          if (-not $data.ok) { Write-Host 'Fixture validation issues detected. (Non-fatal: continuing for now)' }
      - name: Restore previous fixture validation snapshot (cache)
        id: restore_prev_fixture_validation
        uses: actions/cache/restore@v4
        with:
          path: fixture-validation-prev.json
          key: fixture-validation-${{ github.sha }}
          restore-keys: |
            fixture-validation-
      - name: Compute delta vs previous snapshot
        if: steps.restore_prev_fixture_validation.outputs.cache-hit == 'true'
        shell: pwsh
        run: |
          Write-Host 'Previous snapshot restored. Computing delta.'
          pwsh -NonInteractive -File tools/Diff-FixtureValidationJson.ps1 -Baseline fixture-validation-prev.json -Current fixture-validation.json -FailOnNewStructuralIssue > fixture-validation-delta.json
          if ($LASTEXITCODE -eq 3) {
            Write-Host 'New structural fixture issues detected (delta willFail=true).'
            if ($env:FAIL_ON_NEW_STRUCTURAL -eq 'true') {
              Write-Error 'Failing job due to FAIL_ON_NEW_STRUCTURAL=true'
              exit 3
            } else {
              Write-Host 'FAIL_ON_NEW_STRUCTURAL=false -> continuing without failing.'
            }
          }
      - name: Validate delta JSON schema (basic)
        if: steps.restore_prev_fixture_validation.outputs.cache-hit == 'true' && hashFiles('fixture-validation-delta.json') != ''
        shell: pwsh
        run: |
          pwsh -NonInteractive -File tools/Test-FixtureValidationDeltaSchema.ps1 -DeltaJsonPath fixture-validation-delta.json
      - name: Lite schema validate (delta)
        if: steps.restore_prev_fixture_validation.outputs.cache-hit == 'true' && hashFiles('fixture-validation-delta.json') != ''
        shell: pwsh
        run: |
          pwsh -NonInteractive -File tools/Invoke-JsonSchemaLite.ps1 -JsonPath fixture-validation-delta.json -SchemaPath docs/schemas/fixture-validation-delta-v1.schema.json
      - name: Upload fixture validation delta JSON
        if: steps.restore_prev_fixture_validation.outputs.cache-hit == 'true' && hashFiles('fixture-validation-delta.json') != ''
        uses: actions/upload-artifact@v4
        with:
          name: validate-fixture-validation-delta-json
          path: fixture-validation-delta.json
      - name: Upload fixture validation JSON
        uses: actions/upload-artifact@v4
        with:
          name: validate-fixture-validation-json
          path: fixture-validation.json
      - name: Lite schema validate (snapshot)
        shell: pwsh
        continue-on-error: true
        run: |
          if (Test-Path fixture-validation.json) {
            try {
              pwsh -NonInteractive -File tools/Invoke-JsonSchemaLite.ps1 -JsonPath fixture-validation.json -SchemaPath docs/schemas/fixture-manifest-v1.schema.json
              if ($LASTEXITCODE -ne 0) { Write-Host "::notice::Snapshot schema-lite returned $LASTEXITCODE (non-blocking)" }
            } catch { Write-Host '::notice::Snapshot schema-lite skipped or failed (non-fatal).' }
          }
      - name: Append fixture summary
        shell: pwsh
        run: pwsh -NonInteractive -File tools/Write-FixtureValidationSummary.ps1 -ValidationJson fixture-validation.json -DeltaJson fixture-validation-delta.json
      - name: Write fixture summary file
        if: always()
        shell: pwsh
        run: pwsh -NonInteractive -File tools/Write-FixtureValidationSummary.ps1 -ValidationJson fixture-validation.json -DeltaJson fixture-validation-delta.json -SummaryPath fixture-summary.md
      - name: Upload fixture summary artifact
        if: always() && hashFiles('fixture-summary.md') != ''
        uses: actions/upload-artifact@v4
        with:
          name: fixture-validation-summary
          path: fixture-summary.md
      - name: Save current snapshot to cache
        uses: actions/cache/save@v4
        with:
          path: fixture-validation.json
          key: fixture-validation-${{ github.sha }}
      - name: Copy snapshot for next run reference
        shell: pwsh
        run: Copy-Item -LiteralPath fixture-validation.json -Destination fixture-validation-prev.json -Force

  post-gate-help:
    runs-on: ubuntu-latest
    needs: [protect]
    if: ${{ always() && needs.protect.result == 'failure' && github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v5
      - name: Post help comment for Branch Protection Gate
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GH_ADMIN_TOKEN || github.token }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          BASE_REF: ${{ github.event.pull_request.base.ref }}
          HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          $ErrorActionPreference = 'Stop'
          $branchDoc = "https://github.com/$env:HEAD_REPO/blob/$env:HEAD_REF/docs/branch-rules/$env:BASE_REF.md"
          $defaultDoc = "https://github.com/$env:REPO/blob/$env:BASE_REF/docs/BRANCH_RULES.md"
          $settings = "https://github.com/$env:REPO/settings/branches"
          $wf = "https://github.com/$env:REPO/actions/workflows/validate.yml"
          $lines = @(
            '### Branch Protection Gate: missing access or required checks',
            '',
            '- This PR failed the Branch Protection Gate before CI could start.',
            '- Please ensure an admin token is available (secret `GH_ADMIN_TOKEN`, or self-hosted file bootstrap), and that required checks are configured.',
            '',
            "- Branch-specific docs (if present): $branchDoc",
            "- Default branch rules: $defaultDoc",
            "- Branch protection settings: $settings",
            '',
            'Apply labels to proceed (if needed): `/label smoke, test-integration`',
            "One-click retry: $wf",
            '',
            'Once updated, re-run the workflow.'
          ) -join "`n"
          $payload = @{ body = $lines } | ConvertTo-Json -Compress
          $headers = @{ Authorization = "Bearer $env:GH_TOKEN"; Accept = 'application/vnd.github+json'; 'User-Agent'='gate-help-bot' }
          $uri = "https://api.github.com/repos/$env:REPO/issues/$env:PR_NUMBER/comments"
          try { Invoke-RestMethod -Method POST -Uri $uri -Headers $headers -ContentType 'application/json' -Body $payload } catch { Write-Host "::notice::Failed to post help comment: $_" }

  session-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Pester v5 (non-interactive)
        shell: pwsh
        run: |
          try { Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted -ErrorAction SilentlyContinue } catch {}
          Install-Module -Name Pester -MinimumVersion 5.0.0 -Force -Scope CurrentUser -SkipPublisherCheck -Confirm:$false

      - name: Run dispatcher smoke to produce session index
        shell: pwsh
        run: |
          $res = Join-Path $env:RUNNER_TEMP 'sessionindex'
          New-Item -ItemType Directory -Force -Path $res | Out-Null
          ./tools/Quick-DispatcherSmoke.ps1 -ResultsPath $res -PreferWorkspace

      - name: Validate session index schema (schema-lite)
        shell: pwsh
        run: |
          $json = Join-Path $env:RUNNER_TEMP 'sessionindex' 'session-index.json'
          if (-not (Test-Path $json)) { Write-Error "session-index.json not found at $json"; exit 2 }
          pwsh -NonInteractive -File tools/Invoke-JsonSchemaLite.ps1 -JsonPath $json -SchemaPath docs/schemas/session-index-v1.schema.json

      - name: Upload session index artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: validate-session-index
          path: ${{ runner.temp }}/sessionindex/session-index.json
          if-no-files-found: warn
