name: VI Binary Handling Gate
on:
  pull_request:
    paths:
      - '.gitattributes'
      - 'scripts/**'
      - 'tests/ViBinaryHandling.Tests.ps1'
  push:
    branches: [ main ]
    paths:
      - '.gitattributes'
      - 'scripts/**'
      - 'tests/ViBinaryHandling.Tests.ps1'

jobs:
  vi-binary-check:
    uses: LabVIEW-Community-CI-CD/compare-vi-cli-action/.github/workflows/pester-reusable.yml@chore/pester-reusable-rollup
    with:
      include_integration: ${{ 'false' }}
      install_pester: ${{ 'false' }}
      include_patterns: ${{ 'tests/ViBinaryHandling.Tests.ps1' }}
      sample_id: ${{ github.event.inputs.sample_id || '' }}

