name: VI Binary Handling Gate (manual only)
on:
  workflow_dispatch:
    inputs:
      sample_id:
        description: 'Optional run sample identifier for provenance'
        required: false
        default: ''

jobs:
  vi-binary-check:
    uses: ./.github/workflows/pester-reusable.yml
    with:
      include_integration: ${{ 'false' }}
      install_pester: ${{ 'true' }}
      include_patterns: ${{ 'tests/ViBinaryHandling.Tests.ps1' }}
      sample_id: ${{ github.event.inputs.sample_id || '' }}
