name: VI Binary Handling Gate
on:
  pull_request:
    paths:
      - '.gitattributes'
      - 'scripts/**'
      - 'tests/ViBinaryHandling.Tests.ps1'
  push:
    branches: [ main ]
    paths:
      - '.gitattributes'
      - 'scripts/**'
      - 'tests/ViBinaryHandling.Tests.ps1'

jobs:
  vi-binary-check:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Pester (if needed)
        shell: pwsh
        run: |
          if (-not (Get-Module -ListAvailable Pester | Where-Object Version -ge '5.0.0')) {
            Install-Module Pester -MinimumVersion 5.0.0 -Force -Scope CurrentUser
          }

      - name: Run VI binary handling test
        shell: pwsh
        run: |
          $config = New-PesterConfiguration
          $config.Run.Path = 'tests/ViBinaryHandling.Tests.ps1'
          $config.Output.Verbosity = 'Normal'
          Invoke-Pester -Configuration $config

      - name: Upload test artifacts (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: vi-binary-gate-logs
          path: .
